import pygame

# Dimensiones de Pantalla
ANCHO_VENTANA = 800
ALTO_VENTANA = 600
NOMBRE_DEL_JUEGO = "ARKANOID PRO"
CUADROS_POR_SEGUNDO = 60

# Colores (R, G, B)
COLOR_BLANCO = (255, 255, 255)
COLOR_NEGRO = (0, 0, 0)
COLOR_AZUL_BOTON = (50, 50, 150)
COLOR_AZUL_HOVER = (70, 70, 200)
COLOR_GRIS_CLARO = (200, 200, 200)
COLOR_ROJO_ERROR = (200, 50, 50)

# Constantes de Mecánicas
DURACION_POWER_UP_SEGUNDOS = 6
DURACION_POWER_UP_MILISEGUNDOS = DURACION_POWER_UP_SEGUNDOS * 1000 
VELOCIDAD_CAIDA_POWERUP = 3
VELOCIDAD_PELOTA_BASE = 5
RADIO_PELOTA = 13
VELOCIDAD_PALETA = 8
ANCHO_PALETA_ORIGINAL = 170

# Valores de Bloques y Listas
VALORES_PUNTOS_BLOQUES = {"rojo": 100, "verde": 80, "azul": 60, "gris": 40}
LISTA_TIPOS_BLOQUES = ["rojo", "verde", "azul", "gris"]
LISTA_TIPOS_POWER_UP = ["hoja", "fuego", "viento", "gota"]

# --- SONIDO ---
VOLUMEN_MUSICA = 0.3  # 30% (Para que no tape los efectos)
VOLUMEN_EFECTOS = 0.7 # 70% (Más fuerte que la música)